import { Inter, Roboto, Cherry_Swash, Peralta, Oranienbaum } from "next/font/google";
import "./globals.css";

export const inter = Inter({ subsets: ["latin"], weight: ["300"], style: ["normal"] });
const roboto = Roboto({ subsets: ["latin"], style: ["italic"], weight: ["900"] });

export const cherry = Cherry_Swash({ subsets: ["latin"], weight: ["400"] })
export const peralta = Peralta({ subsets: ["latin"], weight: ["400"], style: ["normal"] })
export const oranienbaum = Oranienbaum({ subsets: ["latin"], weight: "400" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
